assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

name: Pech Guillou

permalink: pretty

url: http://pechguillou.nielsenramon.com
